name: "Various Jobs with Dep"

on: ['push']

env:
  var1: ''

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: job1
        run: |
          echo "var1=Hello"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: job2
        run: |
          echo "$var1 World"
