name: "Webhook Event example"

on:
  repository_dispatch:
    types:
      - webhook

jobs:
  respond-to-dispatch:
    if: github.repository == 'victorfim/GitHubExamples/dev'
    runs-on: ubuntu-latest
    steps:
      - name: "Run a script"
        run: 'echo "Event of type: $GITHUB_EVENT_NAME"'
